{{- range .Values.externalServices }}
---
{{- if .enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: {{ .type }}
  externalName: {{ .externalName }}
{{- end }}
{{- end }}

