apiVersion: apps/v1
kind: Deployment
metadata:
  name: uwsgi
  namespace: soarcast
spec:
  selector:
    matchLabels:
      app: uwsgi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: uwsgi
    spec:
      nodeSelector:
        type: soarcast
      containers:
        - volumeMounts:
            - name: staticfiles
              mountPath: /app/staticfiles
            - name: app-config
              mountPath: /mnt/appconfig.json
              subPath: appconfig.json
          image: 121091867024.dkr.ecr.us-east-1.amazonaws.com/isystematics:soarcast-b832b5434588cf5836b2cb0e696f5e87561aaab6-24-dev # {"$imagepolicy": "flux-system:soarcast-image-policy"}
          imagePullPolicy: Always
          name: web
          workingDir: /app
          ports:
            - containerPort: 8000
      volumes:
        - name: staticfiles
          persistentVolumeClaim:
            claimName: soarcast-staticfiles
        - name: app-config
          secret:
            secretName: app-config
