version: '3.0'

services:
    pgdb:
        image: postgres
        env_file:
            - env
        environment:
            - PGDATA=/var/lib/postgresql/data
        volumes:
            - pgdb:/var/lib/postgresql/data:rw
            - ./dump:/dump
        ports:
            - '0.0.0.0:5432:5432'
        restart: always

    web:
        image:
            isystematics/soarcast_web:latest
        depends_on:
            - pgdb
            - redis
        env_file:
            - env
        build:
            context: ./
        links:
            - pgdb
            - redis
        volumes:
            - ./:/app
            - staticfiles:/staticfiles
        restart: always
        ports:
            - "8000:8000"

    nginx:
        image:
            isystematics/soarcast_nginx:latest
        build:
            context: ./nginx
        links:
            - web
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - staticfiles:/staticfiles
        ports:
            - "80:80"
        restart: always

    vault:
        build:
            context: ./vault
        environment:
            - VAULT_ADDR=http://0.0.0.0:8200
            - VAULT_API_ADDR=http://127.0.0.1:8200
        links:
            - web
        command: server -config=/vault/config/vault-config.json
        volumes:
            - ./vault/config:/vault/config:rw
            - ./vault/policies:/vault/policies:rw
            - ./vault/data:/vault/data:rw
            - ./vault/logs:/vault/logs:rw
        ports:
            - "8200:8200"
        cap_add:
            - IPC_LOCK
        restart: always

    redis:
        image: redis:6.2.4-buster
        volumes:
            - redis:/data:rw
        env_file:
            - env
        restart: always

    celery_worker:
        image:
            isystematics/soarcast_celery_worker:latest
        build:
            context: ./
        volumes:
            - ./:/app
        env_file:
            - env
        environment:
            - DJANGO_SETTINGS_MODULE=mission.settings
        entrypoint: ["celery", "-A", "mission", "worker", "--loglevel=INFO", "--pidfile="]
        depends_on:
            - pgdb
            - redis
        restart: always

    celery_beat:
        image:
            isystematics/soarcast_celery_beat:latest
        build:
            context: ./
        volumes:
            - ./:/app
        env_file:
            - env
        environment:
            - DJANGO_SETTINGS_MODULE=mission.settings
        entrypoint: [ "celery", "-A", "mission", "beat", "--loglevel=INFO", "--pidfile="]
        depends_on:
            - pgdb
            - redis
        restart: always
    


volumes:
    staticfiles:
    pgdb:
        driver: local
    redis:
        driver: local