# build.yml
on:
  push:
    paths-ignore:
     - 'kubernetes/**'
     - 'react-frontend/**'
    branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
    - ISOPS-4603         # triggers on pushes that contain changes in master

name: Trivy Container Test Pipeline

# https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: "121091867024"
  AWS_ACCESS_KEY_ID: ${{ secrets.BACKEND_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.BACKEND_AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID_BUCKET:  ${{ secrets.TRIVY_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY_BUCKET:  ${{ secrets.TRIVY_AWS_SECRET_ACCESS_KEY }}
  CONTAINER_IMAGE: isystematics:soarcast-${{ github.sha }}-${{ github.run_number }}-trivy

jobs:
  build-and-push:
    name: Build and deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: django-backend
    steps:

    - name: Checkout
      uses: actions/checkout@master

    # Add steps here like linting, testing, minification, etc.
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.BACKEND_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.BACKEND_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
      
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and tag the image
      run: |
        # Build and tag the image
        docker build \
          -t $CONTAINER_IMAGE \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE ./
           
    # Add additional steps here like scanning of image
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: isystematics:soarcast-${{ github.sha }}-${{ github.run_number }}-trivy
        format: 'json'
        output: Trivy.json
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.BUCKET_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.BUCKET_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Deploy static site to S3 bucket
      run: aws s3 cp Trivy.json s3://d-d-isystematics-librarian/Trivy.json
