# build.yml
on:
  push:
    paths-ignore:
     - 'kubernetes/**'
     - 'react-frontend/**'
    branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
    - ISOPS-4603         # triggers on pushes that contain changes in master

name: Trivy Private Repo Test Pipeline

# https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: "121091867024"
  AWS_ACCESS_KEY_ID: ${{ secrets.TRIVY_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.TRIVY_AWS_SECRET_ACCESS_KEY }}

jobs:
  scan:
    name: Scan Private Repo with Trivy
    runs-on: ubuntu-latest
    
    steps:

    # Add steps here like linting, testing, minification, etc.
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.BACKEND_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.BACKEND_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
           
    # Add additional steps here like scanning of image
    
    - name: Install Trivy
      run: |
        sudo apt install wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt update
        sudo apt install trivy
        
    - name: Scan with Trivy
      run: trivy image -f json -o trivy.json 121091867024.dkr.ecr.us-east-1.amazonaws.com/isystematics:soarcast-ffabfdb027a3a10c32c1b0ff492434a7182cc83c-21-dev 
      
     - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TRIVY_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TRIVY_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Deploy static site to S3 bucket
      run: aws s3 cp trivy.json s3://d-d-isystematics-librarian/trivy.json
